### ISSUE TITLE
Is package abandoned?

### ISSUE THREAD

**Issue by srghma** [f-o-a-m/purescript-optparse#24]
@safareli @kejace @iostat @ryan-foamspace 

Package is broken on purescript 0.14 (there is a pr, but there is a problem with memoize package https://github.com/purescript/package-sets/issues/856), last update on Jun 11, 2019

- what is a status?
- how about move to purescript-contrib?
- how about adding additional maintainers? E.g. You can add me

**Comment by safareli** [comment]
I don't work at FOAM any more and don't have write access on this. plus and I'm not doing PureScript as well so can't help.

Also Adding  @blinky3713 to the conversation.

**Comment by blinky3713** [comment]
@srghma i will add you as a maintainer. If purescript-contrib wants it they can have it, we’re a small company and this library is not critical for us so it doesn’t get a lot of attention

**Comment by srghma** [comment]
@blinky3713 thank you, invitation accepted

> If purescript-contrib wants it they can have it

I dont know what are requirements for packages in purescript-contrib, e.g. is managing CHANGELOG file is required, which is cumbersome

but anyway it's better leave repo at https://github.com/f-o-a-m/purescript-optparse

I'll make sure it's up to date

**Comment by srghma** [comment]
> and this library is not critical for us

it's actually weird that noone raised attention as this library is not included to package-sets in purs 0.14, because this is the only optparse for purescript, I mean it is critical ... for community)

**Comment by blinky3713** [comment]
🤷‍♂️ 

No one has complained about it. We only use this in one package/tool: [chanterelle](https://github.com/f-o-a-m/chanterelle) which is on 0.13.
